# usage: gcloud builds submit

steps:
# build image and push it to container registry
- id: build
  name: gcr.io/kaniko-project/executor
  args:
  - --destination=gcr.io/$PROJECT_ID/gcloud:latest
  - --cache=true
  - --cache-ttl=12h
  - --verbosity=error
