variable "name" {}
variable "location" {}
variable "network" {}
variable "subnetwork" {}
variable "project" {}
variable "org_domain" {}
variable "cluster_secondary_range_name" {}
variable "services_secondary_range_name" {}
variable "master_ipv4_cidr_block" {}
