apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        # - --google-project=project_name # Use this to specify a project different from the one external-dns is running inside
        # - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --source=ingress
        - --provider=google
        - --registry=txt
        - --txt-owner-id=external-dns-{{ .Values.cluster }}
        # make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --domain-filter={{ .Values.domain }}
        - --fqdn-template={{"{{"}}.Name{{"}}"}}-{{"{{"}}.Namespace{{"}}"}}-{{ .Values.location }}.{{ .Values.domain }}
