apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    iam.gke.io/gcp-service-account: "external-dns@{{ .Values.projectId }}.iam.gserviceaccount.com"
